[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/VividCortex/ewma"
  version = "1.1.1"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "18.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/safefile"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/pidfile"

[[constraint]]
  name = "github.com/hashicorp/go-immutable-radix"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  name = "github.com/jedisct1/dlog"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-clocksmith"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-dnsstamps"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-minisign"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/xsecretbox"

[[constraint]]
  name = "github.com/k-sone/critbitgo"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/service"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.15"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"
